### PR TITLE
1000: add ivan as ecip editor

### PR DESCRIPTION
**Pull request by q9f**
ref #401

### CODE REVIEW

**Comment by gitr0n1n** [comment]
https://github.com/ethereumclassic/ECIPs/issues/401#issuecomment-739417463

I second this nomination for @DirtyRusski . He is an active participant. Very helpful in the mining community socials. I'd be happy to get him to a point where he is fluent with the git process. He would be a great independent editor and would increase security/decentralization in the active editors.

**Comment by gitr0n1n** [comment]
@q9f Can we get some movement on adding these Editor positions?

**Comment by q9f** [comment]
Need at least 2 approvals....

**Comment by q9f** [comment]
if you could approve this @stevanlohja @gitr0n1n I can merge it.

**Comment by q9f** [comment]
Never too late :)

Thanks for considering it anyways :)

**Pull request closed without merging**
