### PR TITLE
Move ECIP-1104 to status Accepted

### PR DESCRIPTION
**Pull request by diega**
I propose to _accept_ the current state of the ECIP

### CODE REVIEW

**Comment by bobsummerwill** [comment]
I do not have permissions to review, but I agree with the change.

**Review by meowsbits — APPROVED** [review]
LGTM. I believe `Accepted` can only be applied 2 weeks after the move to `Last Call`.

**Comment by diega** [comment]
Excellent. `Last Call` was set 11 days ago in #452. I think we can wait 3 more days

**Comment by bobsummerwill** [comment]
That makes sense to me, yes.

**Comment by bobsummerwill** [comment]
Actually, I see no real benefit in waiting just to hit that arbitrary 14 day point, so I will merge now.
That will help with the adoption.

**Pull request merged**
