### PR TITLE
ECIP-0001: Process ECIP-0001, Replacement of ECIP-1000

### PR DESCRIPTION
**Pull request by TokenHash**
This ECIP seeks to replace ECIP-1000: https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md

**Changes:**

1. Clarifies the ECIP process is not a governance system nor constitution.
2. Removes @sorpaas as an editor.
3. Establishes with more clarity that the BIP and EIP are precedents for the ECIP process.
4. Adds language in the "ECIP Status Field" section to make expressly clear that when an ECIP advances in the status chain, it can be reverted, rejected, or withdrawn if flaws are found after the fact.
5. Adds a minimal Code of Conduct for this ECIP process specifically, not for the entire ETC ecosystem.

**This ECIP makes these PRs unnecessary:**

- https://github.com/ethereumclassic/ECIPs/pull/274
- https://github.com/ethereumclassic/ECIPs/pull/258
- https://github.com/ethereumclassic/ECIPs/pull/239

**Numbering Format:**

The format `ECIP-0001` was chosen as a proposal to establish a new numbering sequence based on `0001` and so on, for `process` ECIPs so they show at the top of the specs, the ECIPs website,  and other lists.

### CODE REVIEW

**Comment by sorpaas** [comment]
The background stories:

* https://that.world/~classic/2020/01/24/controversy/
* https://twitter.com/sorpaas/status/1222293062266839040
* https://twitter.com/sorpaas/status/1227656972700352512

Goodbye, ETC!

**Comment by bobsummerwill** [comment]
For the historical record, nobody has asked Wei to “leave”.

All that is being proposed is that his ECIP Editor privileges be revoked (because he has repeatedly abused them) and that we purpose to replace ECIP-1000 with ECIP-0001 because he has abused his position as the author of that process too.

He can still author ECIPs, he can still carry on with his core development work and his valuable work on corepaper, if he chooses.   His work in those domains is highly valued and appreciated.  But ECIP Editor is something different.  It requires soft skills and empathy which are not his forte.

If he leaves ETC entirely that is his own choice.  Nobody is asking for or forcing that.   The drama is of his own creation.

**Comment by TokenHash** [comment]
The "background stories" linked by @sorpaas Sorpaas are good to have his viewpoints and to show how he uses falsehoods and manipulation to continue to obstruct the ECIP process.

His final "Goodbye ETC!" follows his typical pattern of attacks, falsehoods, and when he gets pushback from other participants he immediately threatens to quit.

As @sorpaas is very intelligent and has a high work ethic, he easily, and is welcome, to position himself in a key position in ETC as author of the ECIP process (ECIP-1000), developer of two critical clients (Parity and Multi-Geth), and "editor" in the ECIP-process.

However, as seen on various ECIP PRs and documented discussions, he also has been:

• Extremely disruptive in the process
• Has claimed that rules exists when they don't
• Accused various other participants of not following the process thus wishing bugs and vulnerabilities in ETC mainnet
• Has claimed the ECIP process is as immutable as the blockchain when it's juts a production process subject to adjustment, especially if there are bugs or flaws found after the fact
• Has doxxed other editors of the ECIP process who wished to remain pseudonymous
• Finally he has threatened to leave, which, as he is a key figure in the ECIP process and development as explained above, is his leverage to force others to follow his demands

As an author of this ECIP-0001 I decided to write this new process to remove him as an author and editor, to clarify all the non-written rules he claims exist but don't, and welcome that he departs permanently from all his voluntary functions in ETC. I also request the "owners" of this repo to remove him from the organization completely so his ability to continue to disrupt the ECIP process, through his write and merge rights, is minimized.

**Comment by drd34d** [comment]
> For the historical record, nobody has asked Wei to “leave”.

nice try to save face but your boy donald seems to have not read the memo.

> All that is being proposed is that his ECIP Editor privileges be revoked (because he has repeatedly abused them) 

the only abuse here comes from team **krykoder**. this outcome was expected since you petty people started playing this Afri drama.

> and that we purpose to replace ECIP-1000 with ECIP-0001 because he has abused his position as the author of that process too.

Can't you honestly tell who's abusing the process right now?

> He can still author ECIPs, he can still carry on with his core development work and his valuable work on corepaper, if he chooses. 

yeah that's the definition of volunteer. thanks *rolls eyes*

> His work in those domains is highly valued and appreciated. But ECIP Editor is something different. It requires soft skills and empathy which are not his forte.

This is an admission that he is being pushed out for not having **soft skills and empathy** (_aka didn't keep his mouth shut when you started rushing code_). 

'Not his forte' according to your expertise and sole judgement alone or do you have some proof of this that you'd like to present?

> If he leaves ETC entirely that is his own choice. Nobody is asking for or forcing that. The drama is of his own creation.

your boy donald seems to really not have read that memo. By the way, would your expertise in soft skills and empathy say that it's donald's forte? anyone else you'd like to declare socially inapt? 

anyway... good volunteer devs don't stick around forever neither the paid ones. 

free tip: why not go back to the secondary plan and stick with the ECLIP repo instead? Doesn't seem anyone cares anymore that would be a nice power move for the investors ;) 

I'm sure the bosses would love that idea. You're welcome :)

**Comment by TokenHash** [comment]
Recently I commented on Discord that I would give @sorpaas the benefit of the doubt and expected that perhaps he would reconsider being over focused on "process" and decided to continue building in the ETC ecosystem. If he did reconsider, I offered to take out his proposed removal from this ECIP-0001, thus leaving him as an editor.

However, today: 

A) he not only didn't deny that he knew about a flaw in ECIPs he was pushing, which is very concerning in itself, but 

B) he insisted that implementing changes, even with flaws known to him, is perfectly necessary because according to him it is more important to follow the process and what "the community" decides than prioritizing the security of the network.

As B is such an extreme lack of judgement and A just plain malicious, I am no longer giving him the benefit of the doubt and continue to recommend his removal as editor and if possible removal from the ETC Github organization in general.

I am posting his tweets here to back of what I wrote above:

Screen Shot 2020-02-20 at 7 00 32 PM

**Pull request merged**
