### PR TITLE
fix: update ecip editors, withdraw inactive ecips

### PR DESCRIPTION
**Pull request by stevanlohja**
- updated ECIP editors
- set respective ECIPs to `withdrawn` status
This fixes https://github.com/ethereumclassic/ECIPs/issues/453 which has further references to substantiate these changes.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Where are you sourcing the Editors list for review @stevanlohja ?

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
I looks like this is editing a withdrawn ECIP-0001. The active document is ECIP-1000

Can you shuffled the inactive ECIP editors to the inactive list, opposed to removing them.

https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md

**Comment by stevanlohja** [comment]
> I looks like this is editing a withdrawn ECIP-0001. The active document is ECIP-1000
> 
> Can you shuffle the inactive ECIP editors to the inactive list, opposed to removing them as displayed on ECIP-1000
> 
> https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md

Yes. Now check latest commit.

**Review by gitr0n1n — APPROVED** [review]

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Pull request merged**
