### PR TITLE
Set Spiral Mordor activation block

### PR DESCRIPTION
**Pull request by diega**

### CODE REVIEW

**Review by meowsbits — APPROVED** [review]

**Review by ziogaschr — APPROVED** [review]

**Comment by meowsbits** [comment]
This places the Mordor testnet activation around November 7, 2023.

**Review by gitr0n1n — APPROVED** [review]

**Comment by gitr0n1n** [comment]
Small detail, shouldn't our PoW testnet simply be called "Mordor Testnet", opposed to "Mordor Classic Testnet"?

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
Line 41: Change "Mordor Classic testnet" to "Mordor testnet". Thanks!

**Review by gitr0n1n — APPROVED** [review]
immaterial typo fix on testnet name.

**Comment by gitr0n1n** [comment]
I'll let you do the honor of the merge @meowsbits .

To the pseudonyms working on this spec. Thanks for maintaining non-contentious compatibility with the greater EVM ecosystem. In doing so, you're helping to keep Ethereum Classic a state of the art EVM.


==============================================

Interoperability at the EVM level of the stack is important because this allows the application layer developers (DApps) to easily deploy their smart contracts on Ethereum Classic's mainnet and many other EVMs with minimal changes to their code. 

With deployment on Ethereum Classic, the application layer contracts are then supported by the enormous and decentralized proof of work network hashrate protecting Ethereum Classic. This provides the developers of those applications with: permissionless accessibility, censorship resistance, and immutability. Put simply, it allows developers to build unstoppable applications. A principle the Ethereum Classic network has lived up to since initial deployment in 2015.

As the most established and secure PoW blockchain with smart contract functionality, this is a huge value to the blockchain space as a whole. Code is law.

**Pull request merged**
