### PR TITLE
doc: Remove Yaz as ECIP Editor

### PR DESCRIPTION
**Pull request by YazzyYaz**
I'm replacing myself with Stevan as ECIP Editor that is representing the ETC Cooperative.

### CODE REVIEW

**Review by q9f — DISMISSED** [review]

**Comment by q9f** [comment]
needs approvals from of everyone @ethereumclassic/ecip-editors

**Review by realcodywburns — APPROVED** [review]
ack

**Comment by BelfordZ** [comment]
Can we make this as seperate PRs?

IMO this is fundamentally 2 separate changes.

**Comment by q9f** [comment]
No need to close this, let's just change this to "Remove Yaz ..."

**Review by q9f — APPROVED** [review]

**Pull request merged**
