### PR TITLE
Fix path of ECIP 1092 "PirlGuard"

### PR DESCRIPTION
**Pull request by q9f**

### CODE REVIEW

**Comment by q9f** [comment]
It seems the WIP bot is stuck?

**Comment by developerkevin** [comment]
Proposals belong here - in the Pull Requests section - not under issues @Dexaran

**Comment by vanhalendlrband** [comment]
No ASIC only chains, no Pirlguard. 

All chains are at risk of attack, I dont see how this is something that even needs to be fixed. Its just how decentralized blockchains work. 

I doubt the attacker will keep outing himself in my opinion and its already a pain to cash out i dont think anyone would risk money to potentially not be able to cash it out. 

Have to do things to attract more miners and maybe trying to appeal to eth miners do you really want to support the demise of eth pow or maybe support a chain that will keep ethash alive? Theres gotta be a way to convince them that Eth has turned their backs on miners and miners should turn their backs on eth and go mine etc. 

Other than that youre altering the functions of decentralized blockchains that all true coins work on and many get attacked and they move on. 

Worst case scenario i say next time he attacks (if there is a next time) roll the chain back in a soft fork and people may want their lost rewards to essentially fund him not being able to access coins, frustrate him/her enough not to bother again

I see too many trying to take this as an opportunity for solutions that dont fix anything or take decentralization away which would be ASIC algos that are highly centralized compared to GPU and would leave ETC at the mercy of a few medium to large ASIC groups (not many can afford those asics)

Pirlguard and ASICs are not going to change anything im sorry to say and its being pushed ad nauseam.

**Comment by q9f** [comment]
@vanhalendlrband please take the discussion to #327

**Comment by gitr0n1n** [comment]
> It seems the WIP bot is stuck?

it is likely the "%" sign in the title or some sort of punctuation that is freezing it up.

**Pull request merged**
