### PR TITLE
Rejected Status ecip-1049

### PR DESCRIPTION
**Pull request by gitr0n1n**
Move ECIP-1049 to `Rejected` status due to inactivity after three years and lack of following the ECIP process. The only immaterial `changes` in the `material redraft` from 2020 were these changes by me in this PR. The author Alex Tsankov simply closed the old draft (13) and opened a new identical draft (394) in November 2020:
https://github.com/ethereumclassic/ECIPs/pull/400/files

The author (Alex Tsankov) has violated the ECIP process and after three years the ECIP-1000 recommends this proposal be pushed to `Rejected` status. It may only be revived if the champions perform the `material redraft` that is compliant with the ECIP-1000 and `materially address the criticism of the proposal` per requests by the community on the CDC 15 call in October 2020.
https://github.com/ethereumclassic/ECIPs/issues/382#issuecomment-703007940
https://vimeo.com/464336957

ECIP-1000 Clause triggering this move to `Rejected` status:

`The ECIP editor may also change the status to Deferred when no progress is being made on the ECIP.`

`An ECIP may only change status from Draft (or Rejected) to Last Call, when the author deems it is complete, has a working implementation (where applicable), and has community plans to progress it to Final status.`

`ECIPs should be changed from Draft or Last Call status, to Rejected, upon request by any person, if they have not made progress in three years. Such a ECIP may be changed to Draft status if the champion provides revisions that meaningfully address public criticism of the proposal, or to Last Call if it meets the criteria required as described in the previous paragraph.`
http://ecips.ethereumclassic.org/ECIPs/ecip-1000

Justification for `Rejected` status:
`The ECIP editor will not unreasonably reject an ECIP.`

`Reasons for rejecting ECIPs include duplication of effort, disregard for formatting rules, being too unfocused or too broad, being technically unsound, not providing proper motivation or addressing backwards compatibility, or not in keeping with the Ethereum Classic philosophy.`
http://ecips.ethereumclassic.org/ECIPs/ecip-1000

Inactivity of this ECIP-1049 can be viewed in the following pdf.
[ECIP-1049-draft-comparison.pdf](https://github.com/ethereumclassic/ECIPs/files/8104838/ECIP-1049-draft-comparison.pdf)

These changes were observed by comparing:
+ the `Finalized ECIP-1049` from September 2020 that failed its push to `Accepted` status on CDC 15, and;
https://github.com/ethereumclassic/ECIPs/pull/379
+ the `material redraft` that sits today.
https://github.com/ethereumclassic/ECIPs/pull/464

The General Public can compare the drafts in a program like Microsoft Word to view this lack of activity for themselves:
+ Original: https://github.com/ethereumclassic/ECIPs/issues/13
+ Redrafted: https://github.com/ethereumclassic/ECIPs/issues/394

### CODE REVIEW

**Comment by gitr0n1n** [comment]
I tried to add you @atoulme due to your ECIP Editor role , but you don't appear to be populating.

**Comment by gitr0n1n** [comment]
I'm going to lock the Conversation on this PR due to the `contentious nature of the proposal`. 

This is merely an ECIP Editor procedural PR, the case for Rejected status is laid out fairly clearly above.

If the other ECIP editors would like to Unlock the Conversation feel free to, but https://github.com/ethereumclassic/ECIPs/issues/460 is likely a better place for that conversation to be had, imo.

**Review by meowsbits — CHANGES_REQUESTED** [review]
> The ECIP editor will not unreasonably reject an ECIP.

**Comment by gitr0n1n** [comment]
> 
As noted:
Justification for Rejected status:
`The ECIP editor will not unreasonably reject an ECIP.`

`Reasons for rejecting ECIPs include duplication of effort, disregard for formatting rules, being too unfocused or too broad, being technically unsound, not providing proper motivation or addressing backwards compatibility, or not in keeping with the Ethereum Classic philosophy.`

All valid reasons to `Reject` the previously abandoned proposal. @bobsummerwill as a new champion is afforded the time to clean this abandoned proposal up.

 + being too unfocused or too broad
 + being technically unsound
 + not providing proper motivation or addressing backwards compatibility
 + not in keeping with the Ethereum Classic philosophy

**Comment by gitr0n1n** [comment]
> > 
> 
> As noted: Justification for Rejected status: `The ECIP editor will not unreasonably reject an ECIP.`
> 
> `Reasons for rejecting ECIPs include duplication of effort, disregard for formatting rules, being too unfocused or too broad, being technically unsound, not providing proper motivation or addressing backwards compatibility, or not in keeping with the Ethereum Classic philosophy.`
> 
> All valid reasons to `Reject` the previously abandoned proposal. @bobsummerwill as a new champion is afforded the time to clean this abandoned proposal up.
> 
> * being too unfocused or too broad
> * being technically unsound
> * not providing proper motivation or addressing backwards compatibility
> * not in keeping with the Ethereum Classic philosophy

Regarding this proposal in `Rejected` status: `Such a ECIP may be changed to Draft status if the champion provides revisions that meaningfully address public criticism of the proposal`

Note "Such a ECIP may be changed to Draft status if the champion provides revisions that meaningfully address public criticism of the proposal"

This has not happened in three years. The hope is this new champion will make this proposal ECIP-1000 compliant.

**Comment by gitr0n1n** [comment]
@bobsummerwill  I'm going to leave this PR open while you work on these identified issues from the ECIP-1000 document.

[ECIP-1049 - ECIP Process Violations.pdf](https://github.com/ethereumclassic/ECIPs/files/8111773/ECIP-1049.-.ECIP.Process.Violations.pdf)


I believe there is more `public criticism` to address from the CDC 15 call, community calls, the GitHub threads, and now the CDC 22. But these basic changes for the ECIP-1000 document should be very helpful in getting this proposal to where it ought to be:
`the champion provides revisions that meaningfully address public criticism of the proposal`

Thanks for participating in the call and stepping up to champion this ECIP and vocalizing intent to approaching the ECIP process in a pragmatic way. :+1:

**Comment by gitr0n1n** [comment]
PR to Adjust to WIP (Work in Progress) while we wait for @bobsummerwill to materially redraft the ECIP-1049 document per CDC 22.
https://github.com/ethereumclassic/ECIPs/pull/483

In the meantime, this PR to reject ECIP-1049 will stay open. The ECIP-1049 proposal will be reviewed in the future for ECIP-1000 compliance.

**Comment by gitr0n1n** [comment]
This proposal has been withdrawn by the champion for many of the reasons cited in the CDC 15 and 22 calls on the topic.

Thus this PR is obsolete due to the withdrawal of the proposal.
https://github.com/ethereumclassic/ECIPs/pull/486

**Pull request closed without merging**
