### PR TITLE
Reject ECIP-1093 "RandomX"

### PR DESCRIPTION
**Pull request by q9f**
reopen #352 

as per reasoning in #333 

@gitr0n1n if you want to reiterate this proposal back in draft status, please schedule another call for the sake of process.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Please see the relevant thread to this topic: https://github.com/ethereumclassic/ECIPs/pull/352

**Comment by q9f** [comment]
I have nothing else to add.

**Comment by gitr0n1n** [comment]
> please schedule another call for the sake of process.

I'm happy to schedule this call for right now in Discord where I will read: https://github.com/ethereumclassic/ECIPs/pull/352#issuecomment-683462765

**Comment by gitr0n1n** [comment]
This call has concluded. I am sorry if you could not make the scheduled call.

Here is a brief recap of the ECIP-1093 call just held in the Discussion Calls channel for anyone that missed it:
- I read this comment out loud: https://github.com/ethereumclassic/ECIPs/pull/352#issuecomment-683462765
- I asked the room if anyone objected to restoring ECIP-1093 back to Draft status.
- No one objected to this action.
- I concluded that the call reached rough consensus on the topic with everyone present for the scheduled call.

Thank you to all those who attended.

**Comment by q9f** [comment]
Please don't troll the process. That's the only protection we have.

Moving back to Draft as per comment above.

For further work on RandomX I would kindly ask you to research the same as the SHA3 team and the Keccak256 team:
- How would a transition look like (1 block, slow mining, hybrid, etc.)?
- What change in difficulty would be required? How do hashrates compare on different hardware (can it be factorized)?
- How would ETC hashrate compare to competitors (Monero, etc.)?

**Comment by gitr0n1n** [comment]
> For further work on RandomX I would kindly ask you to research the same as the SHA3 team and the Keccak256 team:
> 
> * How would a transition look like (1 block, slow mining, hybrid, etc.)?
> * What change in difficulty would be required? How do hashrates compare on different hardware (can it be factorized)?
> * How would ETC hashrate compare to competitors (Monero, etc.)?

Please add this ECIP-1093 feedback to the ECIP discussion thread https://github.com/ethereumclassic/ECIPs/issues/329 . Thank you for closing this PR.

**Comment by developerkevin** [comment]
As this ECIP was rejected on proper grounds, following the ECIP process to a "T", the author, Ronin, must draft a new ECIP while this one stays rejected. Its crucial we don't give one group or individual preferential treatment just because they are incessantly harassing you here and in discord. All he has to do is draft either the same one or make some changes if he wants but it must be a new ECIP to follow the process. Once rejected, an ECIP **cannot** magically be un-rejected.

**Comment by developerkevin** [comment]
Also this process should not be made a mockery of. It's for technical discussion **not politics!**

**Comment by gitr0n1n** [comment]
> As this ECIP was rejected on proper grounds, following the ECIP process to a "T", the author, Ronin, must draft a new ECIP while this one stays rejected. Its crucial we don't give one group or individual preferential treatment just because they are incessantly harassing you here and in discord. All he has to do is draft either the same one or make some changes if he wants but it must be a new ECIP to follow the process. Once rejected, an ECIP **cannot** magically be un-rejected.

I was told i needed to hold a call. Beleive me I don't want to do all this extra stuff just to return my proposal to draft. but lets do it.

**Pull request closed without merging**
