### PR TITLE
ECIP-1099: move epoch duration to accepted

### PR DESCRIPTION
**Pull request by q9f**
moving ecip 1099 to accepted according to the ecip 1000 process.

the review period ended on friday, oct/02 2020 without any further concerns raised.

clients may now publish releases with the activation blocks:

* For the Ethereum Classic main network: `ETCHASH_FORK_BLOCK := 11_700_000` (Epoch 390)
* For the Mordor Classic test network: `ETCHASH_FORK_BLOCK := 2_520_000` (Epoch 82)
* For the Kotti Classic test network, no upgrade is required.

pools and miners should be updated accordingly.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
> ...without any further concerns raised.

This is not factually accurate, objections were raised. You can follow the conversation in the thread.

https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700195204
https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700207291
https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702937742
https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702955560

**Review by GrshkvMkhl — APPROVED** [review]

**Comment by GrshkvMkhl** [comment]
> > ...without any further concerns raised.
> 
> This is not factually accurate, concerns were raised. You can follow the conversation in the thread. @q9f please represent the issues factually as a "Hard Fork Coordinator" of the network. It's unacceptable to not have a factual paper trail in here.
> 
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700195204)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700207291)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702937742)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702955560)

Oh, come on, this is bullshit. 4G cards are the future of ETC :)

**Comment by q9f** [comment]
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700195204)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700207291)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702937742)
> [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702955560)

There are no technical concerns raised.

**Comment by gitr0n1n** [comment]
> > [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700195204)
> > [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-700207291)
> > [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702937742)
> > [#368 (comment)](https://github.com/ethereumclassic/ECIPs/issues/368#issuecomment-702955560)
> 
> There are no technical concerns raised.

Thank you for clarifying your statement for the Github papertrail.

**Review by ZhekaPlays — APPROVED** [review]

**Comment by ZhekaPlays** [comment]
всё ок, замечаний нет.

**Review by bobsummerwill — APPROVED** [review]
LGTM.
Besu development is underway.
See https://github.com/ChainSafe/besu/tree/ed/ecip_1099

**Comment by q9f** [comment]
https://github.com/hyperledger/besu/pull/1421

**Review by meowsbits — APPROVED** [review]

**Pull request merged**
