### PR TITLE
ECBP-1110: Deactivate MESS

### PR DESCRIPTION
**Pull request by meowsbits**
Turn off the artificial finality mechanism [ECBP-1100's MESS (Modified Exponential Scoring)](https://ecips.ethereumclassic.org/ECIPs/ecip-1100) in [Core-Geth](https://github.com/etclabscore/core-geth) for Ethereum Classic.

Rendered document: https://github.com/meowsbits/ECIPs/blob/ecbp1110/_specs/ecip-1110.md

FYI I'll also be updating https://meowsbits.github.io/51-percent-docs/ this week, which provides some useful context.

### CODE REVIEW

**Comment by gitr0n1n** [comment]
To clarify @meowsbits, MESS still exists in the client as a tool should it ever be needed again by client users, but this removes the default activation setting and adjusted the setting to "off" by default?

**Comment by bobsummerwill** [comment]
Discussion ongoing here:  https://github.com/orgs/ethereumclassic/discussions/522

**Comment by gitr0n1n** [comment]
Now that we have a a block set for Mordor. Is this ECIP in a final state for review? @meowsbits Ping me and I'll be happy to approve since there does not appear to be any contention with this ECIP proposal and discussion has been open at:
https://github.com/orgs/ethereumclassic/discussions/522

**Review by gitr0n1n — APPROVED** [review]
Mordor activation set 10 hours ago. Discussion on the topic seems to support this change without any contention. My understanding is the MESS tool is not being removed at the moment, but its default is OFF due to the abundance of friendly/loyal hashrate that is securing the ETC network since Sept 2022.

**Comment by gitr0n1n** [comment]
> Also for status, do we want to update 1100 with "Replaced by 1099" or something to that effect? Or keep as active, since it is still present in the client, but just not turned on by default?

@meowsbits can you comment on this? How should we adjust the status?

**Comment by meowsbits** [comment]
I like your `Replaced` idea on 1100, the original MESS (activation) spec, concurrent with this. Although I think leaving it would be logical too, I guess it will be more understandable if it's association with this 1110 spec is documented.  Will do.

**Comment by meowsbits** [comment]
CI failed because Ruby's `bundler` install failed. Unrelated to changes here, so I'll go ahead with merge and fix the bundler issue later.

https://github.com/ethereumclassic/ECIPs/actions/runs/7463281525/job/20307577984?pr=520
```
Run gem install bundler
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.6.10.210.
Error: Process completed with exit code 1.
```

**Pull request merged**
