### PR TITLE
1099: fix epoch number and add resources

### PR DESCRIPTION
**Pull request by q9f**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
LGTM - thanks!

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Comment by gitr0n1n** [comment]
Can we get this PR merged if the information is accurate. The ECIP is already live on mainnet since Nov 28th. Thanks for the ECIP housekeeping work.

**Comment by q9f** [comment]
yes, we would need another approval

**Review by meowsbits — APPROVED** [review]

**Pull request merged**
