### PR TITLE
Fix author links

### PR DESCRIPTION
**Pull request by gitr0n1n**
Combed the http://ecips.ethereumclassic.org/all for broken author links or mismatched links and updated.

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
It is not obvious that this is referring to GitHub user names, so perhaps we can link them automatically in future, but that would require a pull request to modify the build.

In the meantime, this seems like a reasonable approach.

**Review by IstoraMandiri — APPROVED** [review]

**Review by IstoraMandiri — CHANGES_REQUESTED** [review]
I'm not sure about removing the emails, perhaps ask these authors first?

**Comment by gitr0n1n** [comment]
> I'm not sure about removing the emails, perhaps ask these authors first?
> 
> I think a proper approach would be to include additional fields for Github ID and Emai, and show both in the UI somehow.

Yeah that would be a grat solution. Many of these emails are likely dead likely dead since they are on disbanded teams emails. I thought it was appropriate to update the emails to that authors most recent contact information.

**Comment by IstoraMandiri** [comment]
Right, having checked it out, this is configured in https://github.com/ethereumclassic/ECIPs/blob/master/_includes/authorlist.html, which does support both right now depending on whether the name has an `(@` or an `<`, but will default to email if there's both.

While it is possible, I would rather not have to add additional UI elements as it clutters things up, so I can see why changing everything to github ids makes more sense.

I would like to hear some other maintainers thoughts about this?

**Comment by meowsbits** [comment]
I don't like the change.

The documents in question were written and left as-is by the authors, including this field, their signature.
If you want to maintain an address book, start a new repo.

Further, modifying emails to Github-handles is backwards. The documents should want to be independent of the VCS web app we happen to be using at this point.

**Review by meowsbits — CHANGES_REQUESTED** [review]
I don't like the change.

The documents in question were written and left as-is by the authors, including this field, their signature.
If you want to maintain an address book, start a new repo.

Further, modifying emails to Github-handles is backwards. The documents should want to be independent of the VCS web app we happen to be using at this point.

**Comment by gitr0n1n** [comment]
Sounds good. I'll close this clean-up PR.

**Pull request closed without merging**
