### PR TITLE
Editorial: Fix/ecip 1049

### PR DESCRIPTION
**Pull request by meowsbits**
- [x] add missing `License` field in header
- [x] add missing `Specification` section

Per the bureaucratic regulations at [`ECIP Format and Structure`](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1000.md#ecip-format-and-structure).

### CODE REVIEW

**Review by rur0 — COMMENTED** [review]
LGTM

**Review by bobsummerwill — APPROVED** [review]
LGTM

**Comment by antsankov** [comment]
LGTM

**Comment by gitr0n1n** [comment]
For @bobsummerwill and his staff:
https://github.com/ethereumclassic/ECIPs/pull/465#issuecomment-1047187415

**Review by gitr0n1n — CHANGES_REQUESTED** [review]
For @bobsummerwill and his staff, I hope you find this helpful in bringing this ECIP into compliance with the ECIP process.

https://github.com/ethereumclassic/ECIPs/pull/465#issuecomment-1047187415

**Comment by bobsummerwill** [comment]
I do not see why you have blocked this PR, @gitr0n1n.

These two changes from @meowsbits are free-standing and useful in their own right.

**Review by IstoraMandiri — APPROVED** [review]

**Comment by gitr0n1n** [comment]
> I do not see why you have blocked this PR, @gitr0n1n.
> 
> These two changes from @meowsbits are free-standing and useful in their own right.

The specification did not appear to be up to ECIP-1000 standards- but it certainly is better than none. The intent wasn't to "block" but request changes.

**Pull request merged**
