### PR TITLE
ECIP-1063: Reject "Integrated decentralized oracles and smart contracts"

### PR DESCRIPTION
**Pull request by bobsummerwill**
This is just a bad idea, and is never going to happen.
Sorry, Jesse.
But we should reject this and clear out cognitive load.

### CODE REVIEW

**Comment by soc1c** [comment]
You can't just reject proposals on Github... This needs a process.

**Comment by bobsummerwill** [comment]
This is a proposal.   Let's discuss.

**Comment by bobsummerwill** [comment]
From ECIP-1000:

"Reasons for rejecting ECIPs include duplication of effort, disregard for formatting rules, being too unfocused or too broad, being technically unsound, not providing proper motivation or addressing backwards compatibility, or *not in keeping with the Ethereum Classic philosophy*"

**Comment by bobsummerwill** [comment]
Discussion -> https://github.com/ethereumclassic/ECIPs/issues/205

**Comment by meowsbits** [comment]
Why not discussions here?

**Comment by bobsummerwill** [comment]
@meowsbits Just better to have the discussions in Issues, rather than cluttering the PRs (which should be code reviews) with "peanut gallery".

**Pull request merged**
