### PR TITLE
ECIP 1099: Add block numbers and move to Last Call

### PR DESCRIPTION
**Pull request by q9f**
ref #368 as per decision at call #362 (13)

moving 1099 to last call.

adding block number 11_700_000 for etc mainnet, 2_520_000 for mordor testnet.

cc @iquidus as ecip author

cc @meowsbits for core geth (needs activation on testnet for further evaluation)

cc @gregthegreek for hyperledger besu (same) and @bobsummerwill

### CODE REVIEW

**Review by iquidus — APPROVED** [review]
LGTM

**Review by YazzyYaz — APPROVED** [review]

**Review by bobsummerwill — CHANGES_REQUESTED** [review]
Just playing catch-up here, it is not realistic that Besu code for ECIP-1099 will be ready on such a short timeline, and that will lead to Mordor being "broken" for Besu users.

I would like to suggest that we have an ephemeral testnet, so that Core-Geth developers can test their changes, and Besu can be added to that as soon as possible.   When things are looking healthy on that ephemeral testnet we can set an activation block on Mordor.

**Comment by q9f** [comment]
Adding the `governance` label as you are raising concerns about a `last call` proposal.

If possible, please suggest more appropriate block numbers and we continue working on the 1099 implementation on a temporary testnet in parallel.

**Review by BelfordZ — APPROVED** [review]

**Comment by q9f** [comment]
Putting this on hold for the next call to decide on a better timing.

**Comment by q9f** [comment]
Updated the block numbers:

* For the Ethereum Classic main network: `ETCHASH_FORK_BLOCK := 11_700_000` (Epoch 390)
* For the Mordor Classic test network: `ETCHASH_FORK_BLOCK := 2_520_000` (Epoch 82)

Which basically means 4 weeks for Mordor and 8 weeks for the Classic main network. 

We will discuss this tomorrow in #362

**Comment by BelfordZ** [comment]
LGTM 

blocked by @bobsummerwill - any update?

**Comment by realcodywburns** [comment]
will the berlin HF eips be included in this fork or will there be another later fork for bls12-381 and simple subroutines? Or do we need a thread for the HF separate from this individual ECIP?

**Comment by bobsummerwill** [comment]
@BelfordZ "blocked by @bobsummerwill - any update?"

Still waiting on ChainSafe, I am afraid.

CC @gregthegreek.

**Comment by q9f** [comment]
No rush to merge this, but would be nice if we can agree on numbers later today.

@realcodywburns there is no Berlin hardfork specification yet, so I don't think this will happen this year.

**Review by bobsummerwill — APPROVED** [review]

**Pull request merged**
