### PR TITLE
1099: move to final

### LINKED ISSUE #11: ECIP-1043: Fixed DAG limit restriction
[ECIP-1043: Fixed DAG limit restriction](https://ecips.ethereumclassic.org/ECIPs/ecip-1043)

### LINKED ISSUE #138: ECIP 1043: Fix DAG limit restriction
Discussion page for ECIP 1043: Fixed DAG limit restriction.

### LINKED ISSUE #368: ECIP-1099 Calibrate Epoch Duration
This issue is the discussion for #367 which proposes extending epoch duration.

### PR DESCRIPTION
**Pull request by q9f**
which is active on mordor and mainnet now

closes #11 

closes #138 

closes #368

### CODE REVIEW

**Comment by TheEnthusiasticAs** [comment]
yep, pls

**Comment by gitr0n1n** [comment]
LGTM

**Review by gitr0n1n — APPROVED** [review]
LGTM

**Review by meowsbits — APPROVED** [review]

**Comment by kizoojun01** [comment]
kizoojun01

**Comment by gitr0n1n** [comment]
Can we move this ECIP to `Final` status. it's been live on the mainnet network for two months. Thanks in advance for the ECIP housekeeping.

**Comment by TheEnthusiasticAs** [comment]
the issue #368 can be closed as well!?

**Comment by q9f** [comment]
counting ronins approval as per #401 - merging!

**Pull request merged**
