### PR TITLE
ECBP-1100: Fix curve calculation pseudocode

### PR DESCRIPTION
**Pull request by gtklocker**
Previously `x` was used but not set. To avoid harming readability and keep the parameter with the descriptive name `x` is assigned inside the code.

### CODE REVIEW

**Review by meowsbits — APPROVED** [review]
LGTM

**Review by q9f — APPROVED** [review]

**Comment by q9f** [comment]
Could you please update with base branch so we can merge this? (Or allow maintainer access?) @gtklocker

**Comment by gtklocker** [comment]
It's updated now.

**Comment by q9f** [comment]
Ah damn, I just merged another PR, sorry, could you do it again?

**Comment by gtklocker** [comment]
Done.

**Pull request merged**
