### PR TITLE
Update licensing to Apache 2.0 for ECIP-1061

### PR DESCRIPTION
**Pull request by bobsummerwill**
Update licensing to Apache 2.0, to reflect inclusion of specifications authored by Wei Tang under Apache 2.0 licensing.

### CODE REVIEW

**Comment by shanejonas** [comment]
@soc1c apache 2.0 is to also be used with technical documentation and specs, which i believe applies here.

**Comment by soc1c** [comment]
Ok

**Comment by bobsummerwill** [comment]
@soc1c After the call with Mishi and Eben, I have a better understanding of what would be best moving forward (CC-BY-SA + patent covenant + DCOs (not real name).

I will make a new ECIP about that at some point soon, but in the meantime there is no specific DOWNSIDE to switching to Apache 2.0.   It won't protect us either, but is not actively bad, and gets us past Wei's concern on this specific ECIP.

Please can you approve so we can move on?  Thank you :-)

**Comment by soc1c** [comment]
I abstain. Someone else would have to go ahead with this.

**Comment by bobsummerwill** [comment]
@meowsbits @YazzyYaz @realcodywburns Please could one of you review?  Thanks!

**Pull request merged**
