### PR TITLE
Add ECIP for Reject "ASIC resistance" myth

### PR DESCRIPTION
**Pull request by bobsummerwill**
Informational ECIP:

**"ASIC resistance" is a myth.  The ETC ecosystem rejects this myth.**

Discussion to https://github.com/ethereumclassic/ECIPs/issues/182, please!

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Discussion to https://github.com/ethereumclassic/ECIPs/issues/182, please!

**Comment by bobsummerwill** [comment]
I will create a longer Rationale section in here based on prior discussions, on ETC Summit content from the individual talks and from the mining panel, and based on Discord / Twitter / WeChat / other debate around this ECIP, as that takes shape.

**Comment by zmitton** [comment]
Mostly agree. Not sure myth is the right word. It's a game of whack-a-mole. I think it is the constant "configuring" required to make it work which ETC should reject. It puts too much power to the teams and gives a given software implementation a limited lifespan (before it needs upgrade to avoid ASICs)

**Comment by bobsummerwill** [comment]
Obsoleted by rejection of ProgPOW.   I will just turn this into a blog post instead.

https://github.com/ethereumclassic/ECIPs/pull/193

**Pull request closed without merging**
