### PR TITLE
Rename: Alphabetize Editors List, Add Current Team Association to Current Editors

### PR DESCRIPTION
**Pull request by gitr0n1n**
- ~~move soc1c to former editor list~~ (addressed in PR 468 per requested change)
- update current editors list to github perms.
- add teams of current editors for transparency. proper checks and balances.
- alphabetize Editor lists via handle

Addresses PR:
* https://github.com/ethereumclassic/ECIPs/pull/468

### CODE REVIEW

**Comment by gitr0n1n** [comment]
Not sure what's going on with your account Antoine Toulme ( @atoulme ). I haven't been able to tag you in anything related to ECIP editor tasks.

@realcodywburns can you take a look at ECIP Editor permissions to see if it needs some updating when you have a moment?

**Comment by realcodywburns** [comment]
Screenshot_20220225-051616_Chrome

latest members

**Review by meowsbits — CHANGES_REQUESTED** [review]
- [x] I would like to include \@soc1c's original commit: https://github.com/ethereumclassic/ECIPs/pull/468/commits/397130bd7ce28b301866eae5ed578ba2140bae9e in the version history. Perhaps you can checkout his branch, revert his commit (maintaining a record of it), then make your proposal in a subsequent patch.
- [x]  The addition of alleged institutional associations (according to... you?) to the identities is a substantive and unrelated change. Please remove them.
- [ ]  Please un-re-order the lists so I can read the diff clearly.

**Comment by gitr0n1n** [comment]
> * [x]  I would like to include @soc1c's original commit: [397130b](https://github.com/ethereumclassic/ECIPs/commit/397130bd7ce28b301866eae5ed578ba2140bae9e) in the version history. Perhaps you can checkout his branch, revert his commit (maintaining a record of it), then make your proposal in a subsequent patch.
> * [x]   The addition of alleged institutional associations (according to... you?) to the identities is a substantive and unrelated change. Please remove them.
> * [x]   Please un-re-order the lists so I can read the diff clearly.

Addressed.

**Comment by gitr0n1n** [comment]
> Screenshot_20220225-051616_Chrome
> 
> latest members

It doesn't appear Antoine Toulme ( @atoulme ) has permissions for ECIP Editor. Is he a valid ECIP editor? And do his permissions need to be updated? I believe Stev added him to this document.

**Comment by bobsummerwill** [comment]
This whole PR is all a bit of a mess and it might be best to start again fresh.

I just wanted to confirm that Antoine **is** an ECIP editor, whatever the Github permissions may say.
Those permissions are secondary to the text of the ECIP.

Actions from CDC 20 included adding Antoine and Istora as ECIP editors.
https://github.com/ethereumclassic/ECIPs/issues/453

**Comment by gitr0n1n** [comment]
> This whole PR is all a bit of a mess and it might be best to start again fresh.
> 
> I just wanted to confirm that Antoine **is** an ECIP editor, whatever the Github permissions may say. Those permissions are secondary to the text of the ECIP.
> 
> Actions from CDC 20 included adding Antoine and Istora as ECIP editors. #453

Thanks for confirmation @bobsummerwill ! I'll just close this PR and throw up different ones. I agree its a bit of a mess now with @meowsbits requested changes.

**Pull request closed without merging**
