### PR TITLE
Rename Aztlán as Asgard

### PR DESCRIPTION
**Pull request by bobsummerwill**
Rename Aztlán as Asgard, which is a better known fictional place, easier to remember and has no ambiguity of spelling.

Twitter poll:
https://twitter.com/BobSummerwill/status/1188479134533484545

### CODE REVIEW

**Comment by bobsummerwill** [comment]
The Twitter poll is ecosystem signalling in support of this proposal.

The actually governance happens within the ECIP process, which is why I have created this pull request, for discussion within the ECIP process.

**Comment by soc1c** [comment]
This Twitter poll indicates support for Aztlan.

https://twitter.com/BobSummerwill/status/1188070604286480384

**Comment by drd34d** [comment]
A Twitter poll is definatelly not the place for **any** governance. What's next, a Straw Poll?

Asgard could be too similar to Agharta for the non-english speakers and thus slightly confusing. Don't see a reason to rename Aztlán/Aztlan at this point.

**Comment by bobsummerwill** [comment]
@drd34d The poll was just that.  A poll.  Signalling.

The governance is happening on the #ecips channel in the ETC Discord (and in these comments), where incidentally we seem to have a rough consensus AGAINST any more "A-names".   Need something more different from Atlantis, and should also be easily understood by non-native speakers, yes.

**Comment by YazzyYaz** [comment]
Given that @soc1c changed the spelling to Aztlan (which is the correct spelling for the Aztec realm and is the culturally appropriate way to call it), I see no reason to change the name to Asgard.

This is all bike shedding debates. Let's stick to Agharta and Aztlan and focus our naming efforts on future hardforks by having an open process for people to contribute their names.

**Comment by bobsummerwill** [comment]
Fair enough, @YazzyYaz.  I think, as @stevanlohja highlighted, that:

Atlantis, Agharta and then Aztlán will be confusing for international audiences, but if I am outlier than I am happy to withdraw this proposal.

**Comment by YazzyYaz** [comment]
@bobsummerwill I agree with you on the A lettering. A big part of the future hard forks would be to avoid the name A for a few hardforks post-Aztlan.

**Pull request closed without merging**
