### PR TITLE
WIP: Initial website for ECIPs

### PR DESCRIPTION
**Pull request by bmann**
OK, here's a first PR for #10 -- turning this repo into a Jekyll site.

GH Pages can only build from master, so I've got a preview up on Netlify: https://objective-villani-edc9c9.netlify.com/

I haven't yet gone through the list of ECIPs and added front matter. Anyone is free to do PRs into this same branch to work on this together -- https://github.com/spadebuilders/ECIPs/tree/jekyll

### CODE REVIEW

**Comment by bmann** [comment]
@realcodywburns @pyskell @YazzyYaz any comments / feedback on this?

Anyone with basic markdown editing / Github skills can help work on editing the ECIPs to add front matter if you've got others in the community that want to lend a hand.

**Comment by pyskell** [comment]
@bmann Awesome stuff! Do we need to update headers on all ECIPs so this pulls data correctly?

**Comment by bmann** [comment]
@pyskell no, it can't be a separate repo. I mean, you could do some sort of custom merge with ECIPs in a two step build process, but ideally the workflow is PRs -> merged --> build new site, which is the purpose of making this in Jekyll.

"Just get at the ECIPs" -- they are all in the ecips folder. The other thing is that I would suggest publishing an RSS/Atom feed + JSON feel that contains all the ECIPs and their status, so it can be consumed and re-mixed in different ways.

The only change is:
* renaming of ECIPS folder to `_ecips` to work with default Jekyll settings
* adding minimal YAML front matter to each ECIP, which is pretty readable as a plain Markdown document in any case

See 1010 for an example --> https://github.com/ethereumclassic/ECIPs/blob/c50dd38f623a9cbb7609065feb4844ed09ecde89/_ecips/ECIP-1010.md

**Comment by pyskell** [comment]
@bmann Thanks for the clarifications, all sounds good to me!

**Comment by YazzyYaz** [comment]
@bmann is this an example of minimal YAML header for each ECIP?

---
layout: ecip
ecip: 1010
title: Delay Difficulty Bomb Explosion
author: Igor Artamonov <splix@ethereumclassic.org>
status: Final
type: Standard
created: 2016-09-13
---

**Comment by bmann** [comment]
@YazzyYaz yep!

**Comment by sorpaas** [comment]
@bmann Hope this is not a discouragement for contribution. We only recently finalized the editing process, and I didn't notice your PR when I made the website overhaul. Things should move faster now and if you submit new PRs, it will get merged quickly, at least not like this!

Unfortunately I'll need to close this PR.

**Pull request closed without merging**
