### PR TITLE
Proposing Coordinator Position

### PR DESCRIPTION
**Pull request by TokenHash**
I am proposing the "coordinator" position, a person, technical or not, who checks and corrects the text and format of ECIPs also writing additions or deletions, specifically non-code non-software ECIPs, or copies improvement proposals from other improvement proposal repos, to help off-load work from, and assist editors in correcting and approving such ECIPs. 

I am dropping myself as a candidate, but i recommend to add 2 person in the coordinator position if it is approved.

### CODE REVIEW

**Comment by sorpaas** [comment]
@TokenHash How about naming the position as "Coordinator" or "Project Manager"? I personally feel that sounds much nicer than "Subeditor" and may be able to attract more people to contribute.

**Comment by TokenHash** [comment]
@sorpaas if the position is useful, yes, "Coordinator" sounds good.

**Comment by TheEnthusiasticAs** [comment]
I am for the name "Coordinator" and for Donald

**Comment by soc1c** [comment]
What's the difference between Coordinator and Editor?

**Comment by TokenHash** [comment]
> What's the difference between Coordinator and Editor?

@soc1c it just emerges from what has been happening in practice. A coordinator is like an assistant to editors and ecip authors, but with no technical skills, and no authorization to merge ecips or review software code. A coordinator has time to do housekeeping things.

Examples where I have been assisting editors:

1. I copied ECIP-1055 from ETC Labs Core to Ethereum Classic repo with the authorization of the author.
2. I reviewed and approved the latest ECIPs by Sorpaas (1040, 1068, 1069, etc.) because they were just copies of corresponding EIPs)
3. I reviewed and adapted texts of ECIP-1000
4. I moved ecip-1016 to "withdrawn" and added the original author with the author consent
5. many more actions

the reason for creating the formal "coordinator" position is that I thought to make it formal makes it more transparent as many actions are made by non-editors and that seems irregular in the system unless the "coordinator" role is added

**Comment by sorpaas** [comment]
@TokenHash I disagree with your interpretation that "coordinator" is somehow on a lower level than "editor" and considered to be "assistant". If we consider ECIP to be a team, then editors are software engineers, and coordinators are project managers. Coordinators play an important role in coordinating the ECIP process, especially during hard fork.

I think it's a mistake that you removed yourself from the proposed list. You should add yourself back in.

**Comment by kimisan** [comment]
@TokenHash can you put your name back ?
@bobsummerwill I think it should be good for Donald being a coordinator.
I think @sorpaas , @antsankov Alex, atari and I also have positive view on it ^^

**Comment by TokenHash** [comment]
I apologize I realized for personal reasons I don't think I can guarantee my availability to act as a coordinator systematically, this is why I decided to take my name out.

I understand that position is unique to what I was doing informally and may be confused with "editor". The difference is that "editor" is a technical position and "coordinator" is a non-technical position more focused on advancing the ECIP process, when editors have limited time.

I will close this PR as I will not continue to lead it. If the position is needed someone else can open a PR, but I don't see other people doing that role in the recnt past.

**Pull request closed without merging**
